services:
  - type: web
    name: cloud_first_blueprint
    runtime: node
    region: frankfurt
    plan: free
    branch: main
    buildCommand: npm install
    runCommand: npm start
    envVars:
      - key: DB_CONNECTION_STRING
        fromDatabase:
          name: cloud_first_blueprint_db
          property: connectionString

databases:
    name: cloud_first_blueprint_db
    region: frankfurt
    plan: free
